"""add_telegram_file_id_to_product_images

Revision ID: 09839aaf681e
Revises: add_product_images_table
Create Date: 2026-01-19 01:28:41.297082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09839aaf681e'
down_revision: Union[str, Sequence[str], None] = 'add_product_images_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_images', sa.Column('telegram_file_id', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_images', 'telegram_file_id')
    # ### end Alembic commands ###
