"""Change telegram_id to BigInteger to support 64-bit IDs

Revision ID: 7446947a531a
Revises: 6db09a9b6732
Create Date: 2025-09-24 08:34:53.202699

"""

from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "7446947a531a"
down_revision: Union[str, Sequence[str], None] = "6db09a9b6732"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.alter_column(
            "users",
            "telegram_id",
            existing_type=sa.INTEGER(),
            type_=sa.BigInteger(),
            existing_nullable=False,
        )
    except Exception as e:
        raise RuntimeError(f"Failed to upgrade telegram_id column: {e}") from e
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.alter_column(
            "users",
            "telegram_id",
            existing_type=sa.BigInteger(),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )
    except Exception as e:
        raise RuntimeError(f"Failed to downgrade telegram_id column: {e}") from e
    # ### end Alembic commands ###
