"""refactor delivery logic add pickup points

Revision ID: 894c36f5cffd
Revises: 96989cc2f910
Create Date: 2026-01-16 02:42:27.979976

"""

from typing import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "894c36f5cffd"
down_revision: Union[str, Sequence[str], None] = "96989cc2f910"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Clean up any existing type from failed migrations
    op.execute("DROP TYPE IF EXISTS delivery_type_enum CASCADE")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "delivery_options",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "delivery_type",
            sa.Enum(
                "pickup_store",
                "pickup_locker",
                "pickup_curbside",
                "hyperlocal_instant",
                "hyperlocal_neighborhood",
                "local_same_day",
                "local_next_day",
                "regional_standard",
                "regional_express",
                "national_standard",
                "national_express",
                "national_priority",
                "special_scheduled",
                "special_bulk",
                name="delivery_type_enum",
            ),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("estimated_time", sa.String(length=50), nullable=True),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("free_threshold", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_delivery_options_delivery_type"),
        "delivery_options",
        ["delivery_type"],
        unique=True,
    )
    op.create_table(
        "pickup_points",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("address", sa.Text(), nullable=False),
        sa.Column(
            "pickup_type",
            sa.Enum(name="delivery_type_enum", create_type=False),
            nullable=False,
        ),
        sa.Column("working_hours", sa.String(length=255), nullable=True),
        sa.Column("latitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pickup_points_pickup_type"),
        "pickup_points",
        ["pickup_type"],
        unique=False,
    )
    op.add_column(
        "orders",
        sa.Column(
            "delivery_type",
            sa.Enum(name="delivery_type_enum", create_type=False),
            nullable=False,
            server_default="pickup_store",
        ),
    )
    op.add_column(
        "orders", sa.Column("delivery_option_id", sa.Integer(), nullable=True)
    )
    op.add_column("orders", sa.Column("pickup_point_id", sa.Integer(), nullable=True))
    op.add_column(
        "orders",
        sa.Column(
            "delivery_fee",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
            server_default="0",
        ),
    )
    op.alter_column("orders", "address", existing_type=sa.TEXT(), nullable=True)
    op.create_foreign_key(None, "orders", "pickup_points", ["pickup_point_id"], ["id"])
    op.create_foreign_key(
        None, "orders", "delivery_options", ["delivery_option_id"], ["id"]
    )
    op.drop_column("orders", "delivery_method")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders",
        sa.Column(
            "delivery_method",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=False,
            server_default="pickup",
        ),
    )
    op.drop_constraint(None, "orders", type_="foreignkey")
    op.drop_constraint(None, "orders", type_="foreignkey")
    op.alter_column("orders", "address", existing_type=sa.TEXT(), nullable=False)
    op.drop_column("orders", "delivery_fee")
    op.drop_column("orders", "pickup_point_id")
    op.drop_column("orders", "delivery_option_id")
    op.drop_column("orders", "delivery_type")
    op.drop_index(op.f("ix_pickup_points_pickup_type"), table_name="pickup_points")
    op.drop_table("pickup_points")
    op.drop_index(
        op.f("ix_delivery_options_delivery_type"), table_name="delivery_options"
    )
    op.drop_table("delivery_options")

    # Drop the Enum type
    sa.Enum(name="delivery_type_enum").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
