"""make_order_address_nullable_and_default_delivery_method

Revision ID: aa4f5240c155
Revises: 96989cc2f910
Create Date: 2026-01-15 20:13:05.070129

"""

from typing import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "aa4f5240c155"
down_revision: Union[str, Sequence[str], None] = "96989cc2f910"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("orders", "address", existing_type=sa.TEXT(), nullable=True)
    op.alter_column(
        "orders",
        "delivery_method",
        existing_type=sa.String(length=100),
        server_default="'pickup'",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "orders",
        "delivery_method",
        existing_type=sa.String(length=100),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column("orders", "address", existing_type=sa.TEXT(), nullable=False)
    # ### end Alembic commands ###
